# Storing personal data {#data-storage}

In research, storage of personal data is one of the most common processing 
activities. Assuming you have a legal basis to store personal data, you 
then need to:

- Choose a storage medium that is GDPR-compliant and that provides a sufficient 
level of data protection;
- Take into account procedural and legal aspects, e.g., how will you handle the 
data once they are stored, and for how long will you store the data? 

These aspects of storing personal data are discussed in this chapter. 

### Chapter summary

**Where should I store personal data?**

Use a medium that has been approved by your institution. If you work at Utrecht 
University, and your preferred storage medium is not included in the 
[Storage Finder](https://tools.uu.nl/storagefinder/){target="_blank"}, 
then please contact [RDM Support or your local data manager](#support) to find 
an alternative solution.

**How to store personal data?**

- Apply organisational and technical [safeguards](#privacy-by-design), 
e.g., restrict access, encrypt data, pseudonymise data, specify responsibilities, etc.
- Store (personal) data preferably in a structured, commonly used, machine-readable
and interoperable format: others should be able to open, understand and work 
with your data.

**For how long should I store personal data?**

- Delete or fully anonymise personal data when they are no longer necessary, 
and preferably determine when you will do this in advance.
- In research, you can archive personal data that are necessary for validation 
purposes for a longer period of time, e.g., 10 years or longer.


## Where should I store personal data? {#data-storage-where}

::::keywords
On this page: storage, location, medium, yoda, o-drive, u-drive, usb stick, 
google drive, onedrive, teams, surfdrive, paper, security
::::

If you work at Utrecht University (UU), you can find a suitable storage medium for 
digital research data via the 
[Storage Finder](https://tools.uu.nl/storagefinder/){target="_blank"}. For 
personal data, select Sensitive or Critical (depending on the sensitivity of 
your data) under question 4 about Confidentiality.

Most storage media in this overview are suitable for storing personal data, either 
because they are controlled by UU (e.g., U- and O-drive, Beta File System) or 
because UU has a [Data Processing Agreement](#data-processing-agreement) in 
place with the storage supplier (e.g., Microsoft Office 365, Yoda).

Is your preferred storage medium not included in the storage finder? Contact 
[RDM Support or your local data manager](#support) to find an alternative solution.

:::note
- Consider encrypting your data, especially when using **portable devices** 
(e.g, memory sticks, phones, dictaphones). Portable devices are also not suitable as back-up, 
due to bit rot and being easily lost.
- Physical personal data (e.g., paper questionnaires, informed consent forms) 
should be stored securely too, e.g. in a locked room, cabinet or drawer. You 
should also avoid leaving unsecured copies lying around (e.g., on a desk or printer).
:::

:::warning
**Do not store research data containing personal data on public cloud services**, 
e.g., Google Drive, Dropbox, OneDrive, Box, Mega, iDrive, iCloud, NextCloud, etc. 
These services are not (always) GDPR-compliant and/or may not offer sufficient 
data security. Moreover, UU does not have any formal agreements with these 
services, enabling them to use the data stored on their platforms for their own 
purposes.
:::

## How should I store personal data? {#data-storage-how}

::::keywords
On this page: access control, accountability, interoperability, interoperable,
separate, anonymise, pseudonymise, de-identify
::::

**Once you have chosen a suitable storage medium, you should act in accordance 
with the nature of your data as well**, for example through:

- Controlling access: make sure that only the necessary people have the right 
kind of access (e.g. read/write) to the personal data, and remove their access 
when they do not longer need it (e.g. when someone leaves the research project).   
- Specifying responsibilities, e.g. who is responsible for guarding access to the 
data on both the short and the long term? Make people aware of the confidential 
nature of the data. Tell them what to do in case of a 
[data breach](https://intranet.uu.nl/en/knowledgebase/what-is-a-personal-data-breach){target="_blank"}.
- Procedural arrangements, e.g. capture access conditions in 
[agreements](#agreements) like the consortium agreement, data processing 
agreement or non-disclosure agreement.
- Storing different types of personal data in different places, e.g., research
data should be stored separately from data subjects' contact details.
- Applying other safeguards where appropriate, e.g., [encryption](#encryption), 
[pseudonymisation or anonymisation](#pseudonymisation-anonymisation), etc.).

See [Designing a GDPR-compliant research project](#privacy-by-design) for more tips.

:::fyi
Personal data should be stored in a **"structured, commonly used, machine-readable 
and interoperable format"** ([rec. 68](https://gdpr.eu/Recital-68-Right-of-data-portability/){target="_blank"}). 
In practice, this means that you should consider whether your files are 
structured and named in a logical way, use 
[sustainable file formats](https://dans.knaw.nl/en/file-formats/){target="_blank"}, 
and provide understandable metadata so that others can interpret the data. 
You can read more about this in the RDM guide 
"[Storing and preserving data](https://www.uu.nl/en/research/research-data-management/guides/storing-and-preserving-data){target="_blank"}".
:::

## For how long should I store personal data? {#data-storage-duration}

::::keywords
On this page: retention, storage period, duration, remove, delete
::::

**As per the GDPR, anyone processing personal data can only store those for as 
long as is necessary for prespecified purposes 
([art 5(e)](https://gdpr-info.eu/art-5-gdpr/){target="_blank"}). 
Afterwards, the personal data have to either be fully anonymised or deleted. 
However, there is an exemption for research data, as described below.**

In research, we often see a division in different types of retention periods:

- If the personal data underpin a scientific publication, it is usually necessary 
to archive some personal data for **integrity and validation purposes** 
([art 5(e)](https://gdpr-info.eu/art-5-gdpr/){target="_blank"}), 
because they are part of the research data. At UU, any research data necessary 
for validation should be archived for at least 10 years 
([UU research data policy](https://www.uu.nl/sites/default/files/university_policy_framework_for_research_data_utrecht_university_-_january_2016.pdf){target="_blank"}). 
If this includes personal data, they too should be archived. Importantly, this 
still means that you need to **protect** the personal data, and **limit** the personal 
data stored to the amount necessary for validation 
([art. 89](https://gdpr-info.eu/art-89-gdpr/){target="_blank"})! 
This also implies that you should keep the documentation about the legal basis 
used (e.g., consent forms) during that time, so that you can demonstrate GDPR 
compliance.
- Specific retention periods may apply additionally to specific types of data. 
For example, in the Netherlands there are specific 
[retention periods for medical data](https://english.ccmo.nl/investigators/data-retention-periods-for-medical-research){target="_blank"} 
that range between 10 and 30 years at minimum.
- Personal data that were used for purposes other than answering your 
research question (e.g. contact information) should have their own retention 
policy: they should be removed or anonymised after the retention period 
(e.g. the research project) has ended.

:::fyi
If identification of the data subject is no longer needed for your 
(research) purposes, you do not need to keep storing the personal data just 
to comply with the GDPR, even if it means your data subjects cannot exercise 
their rights ([art. 11](https://gdpr-info.eu/art-11-gdpr/){target="_blank"}).
:::

:::note
For all types of data in your project (incl. to be archived research data), we
recommend to formulate which data you will retain and for how long (for example
in your Data Management Plan), and communicate the (possibly different) 
retention period(s) to data subjects. If you want to change the storage term you 
initially set and communicated for your personal data, please contact your 
[privacy officer](#support).
:::

### Deleting personal data

If you do not need personal data anymore, you must delete it, except when the data
should be archived for validation purposes. When deleting data, it is important 
to make sure that there are no visible or hidden copies being left behind and 
that files cannot be recovered. The 
[Storage Finder](https://tools.uu.nl/storagefinder/){target="_blank"} 
indicates how you can fully delete data on storage media within UU that are 
suitable for personal data. For your own file system, you can use software like 
[BleachBit](https://www.bleachbit.org/){target="_blank"}, 
[BCWipe](https://www.jetico.com/data-wiping/wipe-files-bcwipe){target="_blank"},
[DeleteOnClick](https://www.2brightsparks.com/onclick/help/welcomedeleteonclick.htm){target="_blank"}, 
and [Eraser](https://eraser.heidi.ie/){target="_blank"} to delete data.