# Sharing data for reuse {#data-sharing-reuse}

::::keywords
On this page: publication, publish, share, transfer, open science, open data,
FAIR data, reuse, reproducibility
::::

**In the context of Open Science, it is becoming more important to share data with 
other researchers, so that they can reproduce results and reuse the data to 
answer new research questions. This can be challenging when you work with 
personal data. Here, we list a few options for sharing personal data for reuse 
responsibly, and making datasets that contain personal data 
[Findable, Accessible, Interoperable and Reusable](https://www.uu.nl/en/research/research-data-management/guides/how-to-make-your-data-fair){target="_blank"} 
(FAIR).**

How  you can make your dataset FAIR, from a privacy perspective, depends on 
which scenario applies to you:

- Your data are fully anonymised: you can 
[publish them in a data repository](#publish-anonymous-data).
- Your data cannot be fully anonymised, but you have a 
[legal basis to share them for reuse](#share-reuse-legal-basis): you can share 
them, but possibly with some restrictions.
- Your data cannot be fully anonymised, and you do not have a legal basis to 
share them: you cannot share them, but we discuss 
[some alternatives](#sharing-reuse-alternatives). 

If you are in doubt whether you can share personal data for reuse, please ask 
your [privacy officer](#support) for help. 

## Sharing anonymised data {#publish-anonymous-data}

::::keywords
On this page: anonymous, publication, share, transfer, open science, open data,
FAIR data
::::

If (part of) the data are truly fully anonymous, they are not classified as 
personal data anymore: from a privacy perspective, you can publish this 
anonymised (part of the) dataset 
[in a data repository](https://www.uu.nl/en/research/research-data-management/guides/publishing-and-sharing-data){target="_blank"} 
without restrictions. 

:::warning
The data should indeed be fully anonymous. 
[Here](#pseudonymisation-anonymisation) you can find how you know that your data 
are anonymous. In 
[this preprint](https://doi.org/10.31234/osf.io/ybzu9){target="_blank"}, you 
can find some examples of poorly anonymised (hence still personal) datasets in 
the field of psychology. It can be very difficult to fully anonymise personal 
data, so when in doubt, we recommend to always treat data as personal.
:::

:::warning
Just because data are no longer subject to the GDPR, it does not mean that there 
may not be other concerns for sharing data publicly. For example:

- publishing the data may not be *ethically* responsible when the data can be 
used to discriminate against a group of people.
- data may be someone else’s intellectual property.
:::

:::fyi
Publish your data in a 
[data repository](https://tools.uu.nl/repository-decision-tool/){target="_blank"} 
and include sufficient documentation  and an 
[open license](https://www.uu.nl/en/research/research-data-management/guides/publishing-and-sharing-data){target="_blank"} 
to your dataset, to make your data 
[FAIR](https://www.uu.nl/en/research/research-data-management/guides/how-to-make-your-data-fair){target="_blank"}. 
This way, others can find, access, understand and reuse your data.
:::

## Sharing personal data with a legal basis {#share-reuse-legal-basis}

::::keywords
On this page: pseudonymous, personal, sensitive, share, transfer, open science,
reuse, access control, legal basis, legal ground, data sharing, transparency,
transparent, inform, further processing, secondary use, secondary processing,
safeguards, protection, FAIR data
::::

If you cannot fully anonymise your data, they are still considered personal data. 
In order to share personal data for reuse, you therefore need to consider the 
following steps:

1. Be transparent in your information to data subjects
2. Make sure you have a legal basis
3. Protect the data while sharing
4. Make your personal data FAIR

If you are in doubt whether you can share personal data for reuse, please ask 
your [privacy officer](#support) for help. If you cannot share the personal data 
for reuse, there are still [alternatives](#sharing-reuse-alternatives) you can 
apply to make (characteristics of) your data useful to others.

### 1. Be transparent {#transparent-reuse}

Irrespective of the legal basis you use to share personal data, data subjects 
must be informed about any reuse of their data. This allows them to exercise 
their rights, such as the right to object (if you use public interest) or to 
withdraw their consent (if you use consent). **If data subjects haven’t been 
informed that you will share their data, you cannot share their data**: you have 
not fulfilled your transparency obligation! 

<details><summary><b>Before the start of your project</b></summary>
  <div><p>Include the intention of sharing data in your 
  [information to data subjects](#privacy-notices), how you plan to keep them 
  informed, and how they can exercise [their rights](#data-subject-rights). 
  Avoid language that precludes sharing, such as "your data will remain strictly 
  confidential", and "your data will only be shared with members of the research 
  team".</p>
  <p>If it is not possible to identify the specific data subject that objected or 
  withdrew consent within the dataset, without additional information provided 
  by the data subject themselves, data subjects can simply not exercise those 
  rights anymore. Let data subjects know about this!</p>
  </div>
</details>
<details><summary><b>At the time of data sharing</b></summary>
  <div><p>If you can still identify the data subjects in your dataset at the time 
  of data sharing (e.g., if you still have a keyfile and/or contact information), 
  inform the data subjects specifically about the data sharing process, using 
  appropriate channels such as email 
  ([art. 12](https://gdpr-info.eu/art-12-gdpr/){target="_blank"}, 
  [art. 14](https://gdpr-info.eu/art-14-gdpr/){target="_blank"}): which data are 
  shared, with whom exactly, for which purposes, under which restrictions, and 
  how can data subjects object or withdraw consent?</p>
  <p>If you cannot identify data subjects in the dataset at the time of data sharing 
  (e.g., there is no keyfile/contact information anymore, but the data are not 
  anonymous), inform them indirectly on how their data are being (re)used and 
  if/how they can exercise their rights, via channels that are easily accessible, 
  for example through a project website, newsletter, mailing list, etc.</p>
  </div>
</details>
  
In most cases, the original owner (controller) of the data is responsible for 
informing data subjects and handling requests related to data subjects’ rights, 
unless otherwise agreed.

### 2. Make sure you have a legal basis {#legal-basis-reuse}

When you share personal data with another organisation for their own specified 
reuse, the recipient will likely become a new [controller](#definitions) of the 
personal data. This means that both you and the recipient need a valid legal 
reason to share (you, the owner) and (re)use (recipient) the personal data.

For the **original owner**, there are multiple possibilities to rely on to share 
the data:

<details><summary><b>Further processing for research purposes</b></summary>
  <div>This is a derogation in the GDPR that enables personal data to be further 
  processed (e.g., shared) for *research purposes*, without requiring a new legal 
  basis, as long as sufficient safeguards are in place to protect the data 
  (e.g., pseudonymisation, access control, data transfer agreement, etc, 
  [art. 5(1)(b)](https://gdpr-info.eu/art-5-gdpr/){target="_blank"}, 
  [art. 89](https://gdpr-info.eu/art-89-gdpr/){target="_blank"}). If the data 
  are not shared for research purposes, then this derogation does not apply. 
  **Note**: There is ongoing discussion whether you can rely on this 
  derogation if you used consent to collect the data: sharing that falls 
  outside of the scope of the original consent, may not meet the 
  [specificity criterium](#consent-requirements) and may not be 
  [fair](#lawful-fair-and-transparent) to data subjects. You can rely on it, 
  however, if you used another legal basis to collect the data (e.g., public 
  interest, legitimate interest).
  </div>
</details>
<details><summary><b>Consent for data sharing</b></summary>
  <div>This entails asking explicit consent to share data with others for reuse 
  for specified purposes, before you collect the data. In 
  [this guide](https://www.uu.nl/en/research/research-data-management/guides/informed-consent-for-data-sharing){target="_blank"} 
  you can find more information about that.
  <ul>
    <li>An advantage of this approach is that it gives data subjects a lot of 
    control, and reuse does not have to be limited to scientific research only 
    (as it is with further processing).</li>
    <li>A limitation of this approach is that consent has to be specific in 
    order to be valid. Thus, consent for data sharing is only legitimate when 
    you *additionally* inform data subjects about the *specific* sharing right 
    before you share the data (e.g., with whom specifically will the data be 
    shared and why?), so that data subjects can still withdraw their data sharing 
    consent.</li>
  </ul>
  </div>
</details>
<details><summary><b>Public or legitimate interest</b></summary>
  <div>Public or legitimate interest could in principle also be used as a legal 
  bases to share personal data, when sharing the data is necessary and 
  proportional and it does not override the interests of the data subjects 
  (a [privacy scan](#privacy-scan) is a good way to assess that).
  </div>
</details>
  
<br>
  
**For the recipient**, in most cases the legal basis for reusing the received 
data is public interest (when reused for research purposes), although 
legitimate interest (when reused for non-research purposes) and consent (if the 
recipient can themselves obtain consent from the data subjects) are also 
possible. Using public (and legitimate) interest requires the recipient to 
assess the risks for data subjects against the benefits of using the data for 
their purposes (a [privacy scan](#privacy-scan) is a good way to do that). This 
is necessary because the recipient will become a new controller and therefore 
also has to treat the personal data in a fair, transparent and lawful way. The 
recipient is usually also bound by the restrictions set forth by the original 
owner, which usually happens through a 
[data transfer agreement](#data-transfer-agreement) or custom license (e.g., use 
safeguards to protect the data, do not share the data any further, only use the 
data for the specified purposes, etc.).

:::warning
If you want to share or reuse 
[special categories of personal data](#special-types-personal-data), you may 
still need explicit consent, except when the data subject had made their data 
publicly available themselves, or when obtaining consent would involve an 
unreasonable amount of effort.
:::

### 3. Protect the data while sharing {#protect-sharing-reuse}

Unless you have a legal basis to make personal data publicly available, you 
should aim to protect the personal data also while sharing them. For example:

- Do not share more data than needed; pseudonymise the data as much as possible.
- Put in place an [agreement](#agreements) that forces recipients to treat the 
data confidentially and that clarifies each party’s responsibilities. This is 
especially important if the data will be shared outside the European Economic Area
with countries that do not have an 
[adequate level of data protection](https://ec.europa.eu/info/law/law-topic/data-protection/international-dimension-data-protection/adequacy-decisions_en){target="_blank"}.
- Share the data safely, for example by giving access via a secure 
[storage](#data-storage) environment, or [encrypting](#encryption) the data 
before transferring them.
- Always follow the restrictions that you communicated to data subjects.

### 4. Make your data FAIR {#fair-personal-data}

Personal data or not, you can always make your data Findable, Accessible, 
Interoperable and Reusable:

<details><summary><b>Findable</b></summary>
  <div>Publish your metadata and documentation in a 
  [data repository](https://tools.uu.nl/repository-decision-tool/){target="_blank"} 
  that assigns a persistent identifier to the dataset. Depending on your 
  situation, you may be able to deposit the data there as well (under restricted 
  access).
  </div>
</details>
<details><summary><b>Accessible</b></summary>
  <div>Clearly specify if and how others can access your dataset and make that 
  information publicly available. Some studies have set up a data access 
  protocol in which this is made clear (e.g., data are accessible after signing 
  an agreement, writing a research proposal, helping to collect new data, etc.). 
  You can find an 
  [example here](https://www.uu.nl/sites/default/files/DataAccessProtocol_YOUth_220627.pdf){target="_blank"}.
  </div>
</details>
<details><summary><b>Interoperable</b></summary>
  <div>Structure and document your data so that they are easily understandable 
  for humans and machines (see our 
  [FAIR guide](https://www.uu.nl/en/research/research-data-management/guides/how-to-make-your-data-fair){target="_blank"}).
  </div>
</details>
<details><summary><b>Reusable</b></summary>
  <div>If you only deposited metadata and documentation, add an 
  [open license](https://www.uu.nl/en/research/research-data-management/guides/publishing-and-sharing-data){target="_blank"} 
  to the dataset (e.g., CC0 or CC BY 4.0). If you deposited the personal data 
  in the data repository as well, there will usually be custom terms of use 
  such as the data access protocol mentioned under Accessible.
  </div>
</details>

## Alternatives to sharing personal data {#sharing-reuse-alternatives}

::::keywords
On this page: metadata, documentation, information, publication, share, transfer, 
open science, FAIR data, reproducibility
::::

### Publish metadata and documentation {#publish-metadata}

Even if you cannot share/publish the data, you can still publish non-sensitive 
metadata and documentation surrounding your research project. This allows your 
dataset and documentation to be findable, citable, and in some cases even 
reusable (one person’s metadata is another person’s data!). In order to 
[make the dataset FAIR](https://www.uu.nl/en/research/research-data-management/guides/how-to-make-your-data-fair){target="_blank"}, 
you should include a note on the access restrictions of the dataset and choose 
a good [data repository](https://tools.uu.nl/repository-decision-tool/){target="_blank"}. 
Knowing that your dataset exists can sometimes already be useful information, 
even when the data are not accessible for others. For an example, please refer to 
the use case about the [Open Science Monitor](#open-science-questionnaire).

### Use other techniques and strategies to enable reuse {#reuse-strategies}

There are also more technical alternatives to transferring personal data to others:

- Use solutions that allow others to run analyses on your data, without ever 
needing access to those data (remote data science, see the 
[Secure computing](#secure-computation) chapter).
- Create a [synthetic dataset](#synthetic-data) that others can use to reproduce 
trends or explore the data.
- Only allow [differentially private algorithms](#differential-privacy) to query 
your dataset.
- Publish aggregated (anonymous) data which may still be useful for others 
(e.g., group-level statistics).