# (PART\*) Use Cases

# Data minimisation in a survey {#pet-survey}

For a course, a teacher at the faculty of Veterinary Medicine collected data on 
the health of pets and the pets’ owners. The initial purpose of the survey was 
to create simply datasets for students to learn about statistics. However, 
besides for the course, the teacher also wanted to use the collected data for 
research purposes and share the data with others. In order to do so, the teacher 
created a new version of the survey that asked for less identifiable information 
and could be more easily anonymised. Additionally, the new version of the survey 
informed participants about the legal basis used to process their personal data. 

Here, you can find the survey before and after data minimisation:

<a href="assets/Use-case-minimisation-Before.pdf" target = "_blank" style="text-decoration: none;"><button type="button">Before minimisation</button></a> 
<a href="assets/Use-case-minimisation-After.pdf" target = "_blank" style="text-decoration: none;"><button type="button">After minimisation</button></a>

<br>
Note that the new version of the survey:

- minimises the amount of personal data collected:
  - Student number and pet names are not asked in the new version of the survey.
  - Instead of Age, the new version asks the Age category of  the owner/caretaker.
  - The survey includes questions on Weight and Height. For data publication, 
  they are used to calculate the Body Mass Index (BMI) and deleted after this 
  calculation.
- contains information about the legal basis used to be able to use (legitimate 
interest) and publish (consent) the data for purposes other than education.

# Data pseudonymisation {#youth-pseudonymisation}

Coming soon!

# Publishing metadata {#open-science-questionnaire}

In 2020, the 
<a href = "https://www.uu.nl/en/research/open-science" target = "_blank">Open 
Science Programme of Utrecht University</a> sent out the first 
Open Science monitor. The aim was to gain insights into the awareness, 
attitudes, practices, opportunities and barriers of employees of Utrecht 
University and Utrecht University Medical Center regarding several Open 
Science practices. As the dataset contained a lot of demographic information 
(e.g., gender, age, nationality, position, type of contract, etc.), and all of 
those variables combined could lead to identification, it could not be shared 
publicly. For this particular dataset, full anonymisation was not desirable, 
as that would greatly decrease its scientific value. Therefore, the Open Science 
Programme chose to publish only the metadata and documentation, without sharing 
the data, in order to protect participants’ data while still complying with the
<a href = "https://www.uu.nl/en/research/research-data-management/guides/how-to-make-your-data-fair" target = "_blank">FAIR principles</a>. 

Here’s the strategy they took:

- They published the dataset under 
<a href = "https://doi.org/10.24416/UU01-3L9K99" target = "_blank">restricted 
access on Yoda</a>, so that the dataset was at least Findable and Accessible.
- They shared other relevant documentation publicly:
  - The <a href = "https://doi.org/10.5281/zenodo.5727106" target = "_blank">preregistration</a>.
  - The <a href = "https://doi.org/10.5281/zenodo.5727057" target = "_blank">questionnaire itself</a>, 
  including the information provided to participants.
  - The <a href = "https://doi.org/10.5281/zenodo.5725177" target = "_blank">final report</a> 
  written about the dataset.

Note that in the metadata of all these publications, cross-references to the 
other publications are included to allow for maximum findability of the 
project’s outputs.

# Reusing education data for research {#reuse-education-data}

A research group at the Science faculty wanted to investigate the effects of the 
Covid-19 pandemic on students’ motivation and study success in a specific course. 
To do so, they wanted to analyse:

- Students’ evaluations of the course from both before and during the pandemic.
- Students’ test and final grades in the course from both before and during the pandemic.

The primary researchers already had access to the data for their educational 
activities, and so they wanted to use the data for research purposes. They went 
to their faculty privacy officer to find out how they could reuse these data in 
a responsible way.

The following privacy issues are relevant in this use case:

- **The raw data were identifiable**<br>
The student grades were linked to names, and both the grades and the evaluations 
were linked to student IDs. Moreover, the evaluations could potentially contain 
names of teachers and other personal information, as they consisted of partly 
open-ended questions. To decrease identifiability, the principal investigator and 
a second examiner, who already had access to the students’ data, first removed or 
replaced all names with pseudonyms (both names of student and teachers), and went 
through the open-ended questions to remove potentially directly identifiable 
information. Only after deidentification were the data shared with research 
assistants who performed the main data and content analyses.<br><br>
- **Data subjects’ rights**<br>
Most students had already finished the course, and were not informed about the 
use of their evaluations and grades for this research project. The researchers 
argued that the majority of the students could not be traced anymore to provide 
this information or to enable them to exercise their data subjects’ rights 
(<a href="https://gdpr-info.eu/art-14-gdpr/" target="_blank">art. 14(5)(b)</a>). 
Moreover, in case a student did want to exercise their rights, it would prove 
difficult to retrieve the correct data, as the data were deidentified as soon as 
possible.<br><br>
- **Legal basis**<br>
Students did not provide explicit consent to process their grades and evaluations 
for this research project. Moreover, if they had provided consent, it could be 
argued that the consent was not freely given, as the primary researchers were 
also involved as teachers, and therefore there was a hierarchical relationship 
between the students and the teachers.  For these reasons, consent was not a 
suitable legal basis in this case. Instead, the researchers relied on:
  - **Public interest**: processing students’ data for the course itself is a 
  public task, namely that of providing education. It was the legal basis for 
  the initial data collection.
  - **Further processing for scientific research purposes**: processing data to 
  answer the research question can be considered as secondary use of the 
  students’ personal data. The GDPR does not consider secondary use of personal 
  data for scientific research purposes incompatible with the original purpose 
  (i.e., the original purpose being to provide education and improving the 
  course, <a href="https://gdpr-info.eu/art-5-gdpr/" target="_blank">art. 5(1)(b)</a>). 
  Thus, it was not necessary to rely on a new legal basis for this research 
  project, provided that the data were protected sufficiently: The researchers 
  made sure that the data were well-protected (i.e., minimised, pseudonymised, 
  and access controlled, <a href="https://gdpr-info.eu/art-89-gdpr/" target="_blank">art. 89</a>).