# What are personal data? {#personal-data}

In order to know whether you should comply with the GDPR in your research 
project, the first question to answer is: do you process personal data? To 
answer this question, we need to know: (1) What exactly are personal data, 
and (2) how do you know if you are working with personal data in your research?

The video below introduces what personal data are:

<iframe width="100%" height="400" src="https://www.youtube.com/embed/egVmd_QFY_o?si=STGQR7or90dcgEF3" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

### Definition of personal data {#definition-personal-data}

According to the GDPR, personal data are “any information relating to an 
identified or identifiable natural person” 
([art. 4(1)](https://gdpr-info.eu/art-4-gdpr/){target="_blank"}):

- **Natural person**: Data by themselves (numbers, text, pictures, audio, etc.) 
are not inherently personal. They only become personal when they refer to or 
relate to a **living individual**. When data refer to an organisation, 
deceased person, or group of individuals, they are not considered personal data 
under the GDPR.
- Data are personal if they **relate** to an individual. This means practically 
anything that someone is, has said or done, owns, may think, etc. 
- The person should be **identified or identifiable**. This is the case not 
only through **directly** identifying information, such as names and contact 
information, but also through **indirectly** identifying information, for 
example if you can single someone out or identify them by combining datasets 
(see the [next page](#personal-data-assess)).

## How to assess whether data contain personal data? {#personal-data-assess}
:::keywords
On this page: sensitive data, privacy-sensitive, personal data, when is data 
privacy-sensitive, identifiability, identifier    
Date of last review: 2022-08-23
:::

Whether your data contain personal data depends on which data you are 
collecting (nature) and under which circumstances (context). A date like 
“12 December 1980”, is not personal data – it is just a date. However, that 
date becomes personal data if it refers to someone’s birthday.  

In assessing whether data are personal, you should take into account all the 
means that you and others may **reasonably likely** use to identify your data 
subjects, such as the required money, time, or (future) developments in 
technology ([rec. 26](https://gdpr-info.eu/recitals/no-26/){target="_blank"}).  

Data can be identifiable when:

- <details><summary>They contain **directly identifying information**.</summary>
  <div>For example: name, image, video recording, audio recording, patient 
  number, IP address, email address, phone number, location data, social media 
  data.</div>
  </details>
- <details><summary>It is possible to **single out** an individual</summary>
  <div><p>This can happen when there are unique data points or unique behavioural 
  patterns which can only apply to one person.</p>
  <p>Examples:
  <ul>
    <li>You have a data subject who is 2.10 meters tall. If this is a unique 
    value in your dataset, this distinguishes this person from others and thus 
    can make them identifiable.</li>
    <li>You have a data subject who only follows far-right accounts on Twitter. 
    If they are the only one in your dataset who do so, this distinguishes this 
    person from others and can make them identifiable.</li>
  </ul></p>
  </div></details>
- <details><summary>It is possible to **infer information** about an individual 
based on information in your dataset</summary>
  <div>For example:
  <ul>
    <li>Inferring a medical condition based on registered medications.</li>
    <li>Guessing that someone lives in a certain neighbourhood based on where they go to school.</li>
  </ul></div>
</details>
- <details><summary>It is possible to **link records** relating to an individual.</summary>
<div><p>This can happen when combining multiple variables within your dataset (e.g., demographic 
information, indirect identifiers). However, it can also happen when combining 
your dataset with other datasets (the "Mosaic effect"). In that case, your data 
still contain personal data, even if the data in your own dataset are not 
identifiable by themselves.</p>
<p>Linkage is often possible with demographic information (age, 
  gender, country of origin, education, workplace information, etc.) and 
  indirect identifiers (pseudonyms, device ID, etc.), for example:
  <ul>
    <li>In the year 2000, 
    [87% of the United States population](https://dataprivacylab.org/projects/identifiability/paper1.pdf){target="_blank"} 
    was found to be identifiable using a combination of their ZIP code, gender 
    and date of birth. You can see for yourself on 
    [this website](https://www.ooa.world/){target="_blank"}.</li>
    <li>An agricultural company’s Uniek Bedrijfsnummer (UBN) can be used to 
    search for the address of the company in the 
    [I&R mobile app](https://www.rvo.nl/onderwerpen/identificatie-en-registratie-dieren/app-ir-dieren){target="_blank"}. 
    Often, this address is also the owner’s home address.</li>
    <li>Geographical data tracking individuals are particularly sensitive 
    because of the multiplicity of data points. 
    [This video](https://www.youtube.com/watch?v=Pivd71NYKDA){target="_blank"} 
    nicely explains why.</li>
  </ul>
  </p></div></details>
- <details><summary>De-identification is still **reversible**.</summary>
<div>This often happens when data are pseudonymised, but there is still a way 
to link the pseudonymised data with identifiable data, for example when a 
name-pseudonym key still exists.</div>
</details>

:::fyi
You can assume that you are processing personal data when you collect data 
**directly** from people, even if the results of that collection are anonymous. But 
also when you use data that are **observed or derived from people**, even if those
data were previously collected, made public or used for non-research purposes.
:::

In short, even if you cannot find out someone’s real identity (name, address), 
the data you process can still contain personal data under the GDPR. Besides 
the examples mentioned here, there are many 
[other examples of personal data](https://intranet.uu.nl/system/files/documenten/categories-of-personal-information-en.pdf){target="_blank"}. 
If you need help assessing whether or not your data contain personal data, 
please contact your [privacy officer](#support).

## Special types of personal data {#special-types-personal-data}
:::keywords
On this page: sensitive personal data, sensitive data, special category, special
categories, politics, race, ethnicity, religion, philosophy, dna, 
genetics, genes, fingerprint, physical condition, mental illness, sexual 
identity, gender identity    
Date of last review: 2023-10-02
:::

A few special types of personal data are worth taking note of are **special 
categories of personal data**, and **otherwise sensitive personal data**. These 
types of personal data have additional requirements. If you want to 
process them, please contact your [privacy officer](#support) first.

### Special categories of personal data {#special-categories-of-personal-data}

The GDPR explicitly defines eight "special categories of personal data". 
Personal data of these types are extra sensitive, because they can be used to 
discriminate or exclude people. The following types of personal data are defined 
as "special categories": 

- racial or ethnic origin (e.g., this could also be a combination of name and 
  country of origin, but not necessarily pictures or videos)
- political opinions (in the broadest sense, not only membership of a 
  political party)
- religious or philosophical beliefs (this does not have to be an "official" 
  religion)
- trade union membership
- genetic data (e.g., DNA, 
  [rec. 34](https://gdpr-info.eu/recitals/no-34/){target="_blank"})
- biometric data, but only when meant to uniquely identify someone (e.g., 
  fingerprints, iris scans) 
- data about physical or mental health in the broadest sense (including 
  indications, diagnoses and treatments, 
  [rec. 35](https://gdpr-info.eu/recitals/no-35/){target="_blank"}) 
- sex life or sexual orientation (including gender identity)

It is in principle **prohibited** to process these types of personal data, 
unless an exception applies 
([art. 9](https://gdpr-info.eu/art-9-gdpr/){target="_blank"}). 
For research, the following exceptions to this prohibition are the most 
relevant:

- <details><summary>Data subjects have made the data publicly available themselves</summary>
  <div><p>You can use special categories of personal data when data subjects have 
  made those data publicly available themselves. It must concern *truly public* 
  sources (e.g., TV, newpaper, public social media, blogs, etc.) where the data 
  subject does not expect (some) privacy. Moreover, the data subject must have 
  *intended* to disclose the personal data "as special categories of personal 
  data".</p>
  <p>An example: if someone writes in their blog that they have been voting for 
  a certain political party all their life, they are consciously making that 
  information public. If someone is confined to a wheelchair and posts a holiday 
  selfie (with a wheelchair) on a social medium, it is not about their 
  disability, but about their holiday. Special category personal data derived 
  from this are still protected by the processing ban. The same applies, for 
  example, to personal data that can be derived from combining various separate 
  data sources.</p>
  <p>Publicly accessible special personal data of well-known personalities 
  (celebrities, politicians, etc.) may be processed, whether those data have 
  been made public by the person in question or by someone else.</p>
  </div>
  </details>
- <details><summary>Data subjects have provided explicit consent to process 
  these data for a specific purpose</summary>
  <div>If data subjects have provided explicit consent which satisfies the GDPR
  [criteria for valid consent](#consent-requirements), then you can use the 
  personal data in your research project.</div>
  </details>
- <details><summary>Processing is necessary for scientific research purposes 
  and consent is impossible or unreasonably difficult</summary>
  <div>If you are using the special categories for scientific research purposes
  (incl. historical and statistical purposes), and it is impossible or would 
  take an unreasonable amount of effort to obtain explicit consent 
  ([UAVG art. 24](https://wetten.overheid.nl/BWBR0040940/2021-07-01#Hoofdstuk3){target="_blank"}),
  you can use the data in your research. If this is the case, you must 
  substantiate this danger to your project and take additional protection 
  measures. Obtaining consent could take an unreasonable amount of effort, 
  for example, in:
    <ul>
      <li>large-scale archival research into living people from whom you cannot 
        obtain all or up-to-date contact details</li>
      <li>webscraping or other big data research, in which the time investment to 
        obtain consent is out of proportion</li>
      <li>fieldwork outside Europe. In many non-European communities, placing a 
        signature on a consent form is not trusted. Sometimes people also have 
        very poor reading skills. Proving consent is then virtually impossible</li>
      <li>research within more or less private social media groups.</li>
    </ul>
  </div>
  </details>

Even if you can invoke one of these exemptions, special categories of personal 
data warrant additional security measures to make sure they are protected. 
Always contact your [privacy officer](#support) if you intend on using 
these types of data. 

:::note
The [Dutch Code of Conduct for Health Research](https://www.coreon.org/wp-content/uploads/2023/06/Code-of-Conduct-for-Health-Research-2022.pdf){target="_blank"}
(p.68) specifies a number of exceptions for health researchers in which explicit 
consent for processing special categories of personal data may not be necessary.
:::

### Data that are otherwise sensitive {#data-that-are-otherwise-sensitive}

Other types of data can also be sensitive, because they can carry higher risks 
for the data subjects. These types of data can either not be processed at all, 
or only under certain circumstances. Either way, they require additional 
security measures. Always contact your [privacy officer](#support)
if you intend on using these types of data.

Examples are:

- Financial data
- Data about relationship problems
- Data that can be misused for identity fraud, such as the Dutch Citizen 
  Service Number (BSN).  The BSN can only be used when legally necessary. Since 
  this is not the case for scientific research, using BSN in research is in most 
  cases forbidden.
- Criminal data or data about criminal convictions. These can only be processed 
  under governmental supervision or when a derogation exists in national 
  legislation ([art. 10](https://gdpr-info.eu/art-10-gdpr/){target="_blank"}). 
  For scientific research, more or less the same regime applies for these data 
  as for special categories of personal data. This means that you are allowed 
  to use them for your study if one of the exceptions mentioned for special 
  categories of personal data applies. 